//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type AuditLog struct {
	IDLog          int32 `sql:"primary_key"`
	IDUser         *int32
	Aktivitas      *string
	IPAddress      *string
	WaktuAktivitas time.Time
}
