services:
  warehouse:
    image: docker.io/postgres:18.3-alpine3.23
    restart: unless-stopped
    volumes:
      - ./storage/warehouse:/var/lib/postgresql
      - ./migrations:/docker-entrypoint-initdb.d
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${WAREHOUSE_DB:-imunisasi}
      POSTGRES_USER: ${WAREHOUSE_USER:-postgres}
      POSTGRES_PASSWORD: ${WAREHOUSE_PASSWORD:-postgres}
    ports:
      - ${HOST_IP:-127.0.0.1}:${HOST_PORT:-5433}:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      retries: 10
      timeout: 5s
    profiles: ["warehouse", "dev"]

  master:
    image: docker.io/postgres:18.3-alpine3.23
    restart: unless-stopped
    volumes:
      - ./storage/master:/var/lib/postgresql
      - ./migrations:/docker-entrypoint-initdb.d
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${MASTER_DB:-imunisasi}
      POSTGRES_USER: ${MASTER_USER:-postgres}
      POSTGRES_PASSWORD: ${MASTER_PASSWORD:-postgres}
    ports:
      - ${HOST_IP:-127.0.0.1}:${MASTER_HOST_PORT:-5432}:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      retries: 10
      timeout: 5s
    profiles: ["master", "dev"]

  staging:
    image: mcr.microsoft.com/mssql/server:2025-CU3-ubuntu-22.04
    restart: unless-stopped
    volumes:
      - ./storage/staging:/var/opt/mssql:z
    environment:
      - "ACCEPT_EULA=Y"
    env_file:
      - .env
    ports:
      - ${HOST_PORT:-127.0.0.1}:${STAGING_HOST_PORT:-1433}:1433
    healthcheck:
      test: /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P
        ${STAGING_SA_PASSWORD:-DefaultPassword123!} -C -Q "SELECT 1" || exit 1
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 30s
    profiles: ["staging", "dev"]

  migration-warehouse:
    build:
      context: ./migrations
    develop:
      watch:
        - action: rebuild
          path: /app/Containerfile
    volumes:
      - ./migrations:/app:z
      - go_cache:/go/pkg/mod:z
    working_dir: /app
    environment:
      GOOSE_DRIVER: postgres
      GOOSE_DBSTRING: postgres://${WAREHOUSE_USER:-postgres}:${WAREHOUSE_PASSWORD:-postgres}@warehouse:5432/${WAREHOUSE_DB:-imunisasi}
      GOOSE_MIGRATION_DIR: /app/warehouse
    env_file:
      - .env
    depends_on:
      warehouse:
        condition: service_healthy
    command: sh -c "goose up && sh"
    profiles: ["migration", "warehouse", "dev"]

  migration-master:
    build:
      context: ./migrations
    develop:
      watch:
        - action: rebuild
          path: /app/Containerfile
    volumes:
      - ./migrations:/app:z
      - go_cache:/go/pkg/mod:z
    working_dir: /app
    environment:
      GOOSE_DRIVER: postgres
      GOOSE_DBSTRING: postgres://${MASTER_USER:-postgres}:${MASTER_PASSWORD:-postgres}@master:5432/${MASTER_DB:-imunisasi}
      GOOSE_MIGRATION_DIR: /app/master
    env_file:
      - .env
    depends_on:
      master:
        condition: service_healthy
    command: sh -c "goose up && sh"
    profiles: ["migration", "master", "dev"]

  migration-staging:
    build:
      context: ./migrations
    develop:
      watch:
        - action: rebuild
          path: /app/Containerfile
    volumes:
      - ./migrations:/app:z
      - go_cache:/go/pkg/mod:z
    working_dir: /app
    environment:
      GOOSE_DRIVER: mssql
      GOOSE_DBSTRING: sqlserver://${STAGING_USER:-sa}:${STAGING_PASSWORD:-DefaultPassword123!}@staging:1433/${STAGING_DB:-imunisasi}
      GOOSE_MIGRATION_DIR: /app/staging
    env_file:
      - .env
    depends_on:
      staging:
        condition: service_healthy
    command: sh -c "goose up && sh"
    profiles: ["migration", "staging", "dev"]

volumes:
  go_cache:
