// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graphql

type CreateArtikelInput struct {
	Judul      string  `json:"judul"`
	IsiArtikel string  `json:"isiArtikel"`
	Kategori   *string `json:"kategori,omitempty"`
}

type Mutation struct {
}

type Query struct {
}

type ReviewArtikelInput struct {
	Aksi          string  `json:"aksi"`
	CatatanReview *string `json:"catatanReview,omitempty"`
}

type UpdateArtikelInput struct {
	Judul      *string `json:"judul,omitempty"`
	IsiArtikel *string `json:"isiArtikel,omitempty"`
	Kategori   *string `json:"kategori,omitempty"`
}
