package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.95

import (
	"context"
	"slices"

	artikelDomain "github.com/stringptr/SiGizi/backend/internal/domain/artikel"
	"github.com/stringptr/SiGizi/backend/internal/errorutils"
	"github.com/stringptr/SiGizi/backend/internal/httputils"
	"github.com/stringptr/SiGizi/backend/internal/pagination"
)

// Penulis is the resolver for the penulis field.
func (r *artikelResolver) Penulis(ctx context.Context, obj *Artikel) (*User, error) {
	if loaders := LoadersFromContext(ctx); loaders != nil {
		name := loaders.UserLoader.GetUser(ctx, int32(obj.IDPenulis))
		return &User{IDUser: obj.IDPenulis, Nama: name}, nil
	}
	return &User{IDUser: obj.IDPenulis}, nil
}

// Verifikator is the resolver for the verifikator field.
func (r *artikelResolver) Verifikator(ctx context.Context, obj *Artikel) (*User, error) {
	if obj.IDVerifikator == nil {
		return nil, nil
	}
	if loaders := LoadersFromContext(ctx); loaders != nil {
		name := loaders.UserLoader.GetUser(ctx, int32(*obj.IDVerifikator))
		return &User{IDUser: *obj.IDVerifikator, Nama: name}, nil
	}
	return &User{IDUser: *obj.IDVerifikator}, nil
}

// Penulis is the resolver for the penulis field.
func (r *artikelListItemResolver) Penulis(ctx context.Context, obj *ArtikelListItem) (*User, error) {
	if loaders := LoadersFromContext(ctx); loaders != nil {
		name := loaders.UserLoader.GetUser(ctx, int32(obj.IDPenulis))
		return &User{IDUser: obj.IDPenulis, Nama: name}, nil
	}
	return &User{IDUser: obj.IDPenulis}, nil
}

// Penulis is the resolver for the penulis field.
func (r *artikelPendingItemResolver) Penulis(ctx context.Context, obj *ArtikelPendingItem) (*User, error) {
	if loaders := LoadersFromContext(ctx); loaders != nil {
		name := loaders.UserLoader.GetUser(ctx, int32(obj.IDPenulis))
		return &User{IDUser: obj.IDPenulis, Nama: name}, nil
	}
	return &User{IDUser: obj.IDPenulis}, nil
}

// CreateArtikel is the resolver for the createArtikel field.
func (r *mutationResolver) CreateArtikel(ctx context.Context, input CreateArtikelInput) (*CreateArtikelPayload, error) {
	claims := httputils.GetAccessClaim(ctx)
	if claims == nil {
		return nil, &errorutils.Error{Status: 401, Message: "Silahkan login terlebih dahulu."}
	}

	svc := r.Resolver.ArtikelService
	isDinkes := slices.Contains(claims.Roles, "DINKES")

	data, err := svc.Create(ctx, claims.IDUser, isDinkes, &artikelDomain.CreateArtikelRequest{
		Judul:      input.Judul,
		IsiArtikel: input.IsiArtikel,
		Kategori:   safePtrStr(input.Kategori),
	})
	if err != nil {
		return nil, err
	}

	return &CreateArtikelPayload{
		IDArtikel:     int(data.IDArtikel),
		StatusArtikel: data.StatusArtikel,
	}, nil
}

// UpdateArtikel is the resolver for the updateArtikel field.
func (r *mutationResolver) UpdateArtikel(ctx context.Context, id int, input UpdateArtikelInput) (*Artikel, error) {
	claims := httputils.GetAccessClaim(ctx)
	if claims == nil {
		return nil, &errorutils.Error{Status: 401, Message: "Silahkan login terlebih dahulu."}
	}

	svc := r.Resolver.ArtikelService
	isDinkes := slices.Contains(claims.Roles, "DINKES")

	detail, err := svc.Update(ctx, claims.IDUser, isDinkes, &artikelDomain.UpdateArtikelRequest{
		Judul:      input.Judul,
		IsiArtikel: input.IsiArtikel,
		Kategori:   input.Kategori,
	}, int32(id))
	if err != nil {
		return nil, err
	}

	return &Artikel{
		IDArtikel:      int(detail.IDArtikel),
		Judul:          detail.Judul,
		IsiArtikel:     detail.IsiArtikel,
		Kategori:       strPtr(detail.Kategori),
		StatusArtikel:  detail.StatusArtikel,
		TanggalPublish: detail.TanggalPublish,
		CreatedAt:      detail.CreatedAt,
		UpdatedAt:      detail.UpdatedAt,
	}, nil
}

// DeleteArtikel is the resolver for the deleteArtikel field.
func (r *mutationResolver) DeleteArtikel(ctx context.Context, id int) (bool, error) {
	claims := httputils.GetAccessClaim(ctx)
	if claims == nil {
		return false, &errorutils.Error{Status: 401, Message: "Silahkan login terlebih dahulu."}
	}
	if !slices.Contains(claims.Roles, "DINKES") && !slices.Contains(claims.Roles, "SUPER_ADMIN") {
		return false, &errorutils.Error{Status: 403, Message: "Tidak mempunyai akses."}
	}

	svc := r.Resolver.ArtikelService
	err := svc.Delete(ctx, int32(id))
	if err != nil {
		return false, err
	}
	return true, nil
}

// ReviewArtikel is the resolver for the reviewArtikel field.
func (r *mutationResolver) ReviewArtikel(ctx context.Context, id int, input ReviewArtikelInput) (*ReviewArtikelPayload, error) {
	claims := httputils.GetAccessClaim(ctx)
	if claims == nil {
		return nil, &errorutils.Error{Status: 401, Message: "Silahkan login terlebih dahulu."}
	}
	if !slices.Contains(claims.Roles, "DINKES") && !slices.Contains(claims.Roles, "SUPER_ADMIN") {
		return nil, &errorutils.Error{Status: 403, Message: "Tidak mempunyai akses."}
	}

	svc := r.Resolver.ArtikelService
	data, err := svc.Review(ctx, claims.IDUser, int32(id), &artikelDomain.ReviewArtikelRequest{
		Aksi:          input.Aksi,
		CatatanReview: safePtrStr(input.CatatanReview),
	})
	if err != nil {
		return nil, err
	}

	return &ReviewArtikelPayload{
		IDArtikel:      int(data.IDArtikel),
		StatusArtikel:  data.StatusArtikel,
		TanggalPublish: data.TanggalPublish,
	}, nil
}

// Artikel is the resolver for the artikel field.
func (r *queryResolver) Artikel(ctx context.Context, id int) (*Artikel, error) {
	repo := r.Resolver.ArtikelRepo

	article, err := repo.GetByID(ctx, int32(id))
	if err != nil {
		return nil, err
	}
	if article == nil {
		return nil, &errorutils.Error{Status: 404, Message: "Artikel tidak ditemukan."}
	}

	detail, err := repo.GetDetailJoinByID(ctx, int32(id))
	if err != nil {
		return nil, err
	}

	// Batch-load penulis and verifikator names via DataLoader.
	if loaders := LoadersFromContext(ctx); loaders != nil {
		ids := []int32{article.IDPenulis}
		if article.IDVerifikator != nil {
			ids = append(ids, *article.IDVerifikator)
		}
		ctx = loaders.UserLoader.BatchLoad(ctx, ids)
	}

	a := &Artikel{
		IDArtikel:      int(article.IDArtikel),
		Judul:          article.Judul,
		IsiArtikel:     article.IsiArtikel,
		Kategori:       article.Kategori,
		StatusArtikel:  string(article.StatusArtikel),
		IDPenulis:      int(article.IDPenulis),
	}

	if detail != nil {
		a.TanggalPublish = detail.TanggalPublish
		a.CreatedAt = detail.CreatedAt
		a.UpdatedAt = detail.UpdatedAt
	} else {
		created := article.CreatedAt.Format("2006-01-02T15:04:05Z07:00")
		updated := article.UpdatedAt.Format("2006-01-02T15:04:05Z07:00")
		a.CreatedAt = created
		a.UpdatedAt = updated
	}

	if article.IDVerifikator != nil {
		idVer := int(*article.IDVerifikator)
		a.IDVerifikator = &idVer
	}

	return a, nil
}

// DaftarArtikel is the resolver for the daftarArtikel field.
func (r *queryResolver) DaftarArtikel(ctx context.Context, page *int, perPage *int) (*ArtikelListPayload, error) {
	svc := r.Resolver.ArtikelService
	p := pagination.ValidatePage(ptrToInt(page))
	pp := pagination.ValidatePerPage(ptrToInt(perPage))

	data, err := svc.GetAllPublished(ctx, &artikelDomain.GetAllPublishedRequest{
		Page:    p,
		PerPage: pp,
	})
	if err != nil {
		return nil, err
	}

	// Batch-load all penulis names via DataLoader.
	if loaders := LoadersFromContext(ctx); loaders != nil {
		ids := make([]int32, 0, len(data.Artikel))
		for _, item := range data.Artikel {
			ids = append(ids, item.IDPenulis)
		}
		ctx = loaders.UserLoader.BatchLoad(ctx, ids)
	}

	items := make([]*ArtikelListItem, len(data.Artikel))
	for i, item := range data.Artikel {
		items[i] = &ArtikelListItem{
			IDArtikel:      int(item.IDArtikel),
			Judul:          item.Judul,
			Kategori:       item.Kategori,
			Ringkasan:      item.Ringkasan,
			IDPenulis:      int(item.IDPenulis),
			TanggalPublish: item.TanggalPublish,
			StatusArtikel:  item.StatusArtikel,
		}
	}

	return &ArtikelListPayload{
		Items: items,
		Meta: &PageInfo{
			CurrentPage: int(data.Meta.CurrentPage),
			PerPage:     int(data.Meta.PerPage),
			Total:       int(data.Meta.Total),
			LastPage:    int(data.Meta.LastPage),
		},
	}, nil
}

// DaftarArtikelSemua is the resolver for the daftarArtikelSemua field.
func (r *queryResolver) DaftarArtikelSemua(ctx context.Context, page *int, perPage *int) (*ArtikelListPayload, error) {
	claims := httputils.GetAccessClaim(ctx)
	if claims == nil {
		return nil, &errorutils.Error{Status: 401, Message: "Silahkan login terlebih dahulu."}
	}
	if !slices.Contains(claims.Roles, "ADMIN") && !slices.Contains(claims.Roles, "SUPER_ADMIN") {
		return nil, &errorutils.Error{Status: 403, Message: "Tidak mempunyai akses."}
	}

	svc := r.Resolver.ArtikelService
	p := pagination.ValidatePage(ptrToInt(page))
	pp := pagination.ValidatePerPage(ptrToInt(perPage))

	data, err := svc.GetAll(ctx, &artikelDomain.GetAllPublishedRequest{
		Page:    p,
		PerPage: pp,
	})
	if err != nil {
		return nil, err
	}

	if loaders := LoadersFromContext(ctx); loaders != nil {
		ids := make([]int32, 0, len(data.Artikel))
		for _, item := range data.Artikel {
			ids = append(ids, item.IDPenulis)
		}
		ctx = loaders.UserLoader.BatchLoad(ctx, ids)
	}

	items := make([]*ArtikelListItem, len(data.Artikel))
	for i, item := range data.Artikel {
		items[i] = &ArtikelListItem{
			IDArtikel:      int(item.IDArtikel),
			Judul:          item.Judul,
			Kategori:       item.Kategori,
			Ringkasan:      item.Ringkasan,
			IDPenulis:      int(item.IDPenulis),
			TanggalPublish: item.TanggalPublish,
			StatusArtikel:  item.StatusArtikel,
		}
	}

	return &ArtikelListPayload{
		Items: items,
		Meta: &PageInfo{
			CurrentPage: int(data.Meta.CurrentPage),
			PerPage:     int(data.Meta.PerPage),
			Total:       int(data.Meta.Total),
			LastPage:    int(data.Meta.LastPage),
		},
	}, nil
}

// DaftarArtikelPending is the resolver for the daftarArtikelPending field.
func (r *queryResolver) DaftarArtikelPending(ctx context.Context, page *int, perPage *int) (*ArtikelPendingPayload, error) {
	claims := httputils.GetAccessClaim(ctx)
	if claims == nil {
		return nil, &errorutils.Error{Status: 401, Message: "Silahkan login terlebih dahulu."}
	}
	if !slices.Contains(claims.Roles, "DINKES") && !slices.Contains(claims.Roles, "SUPER_ADMIN") {
		return nil, &errorutils.Error{Status: 403, Message: "Tidak mempunyai akses."}
	}

	svc := r.Resolver.ArtikelService
	p := pagination.ValidatePage(ptrToInt(page))
	pp := pagination.ValidatePerPage(ptrToInt(perPage))

	data, err := svc.GetPending(ctx, &artikelDomain.GetPendingRequest{
		Page:    p,
		PerPage: pp,
	})
	if err != nil {
		return nil, err
	}

	if loaders := LoadersFromContext(ctx); loaders != nil {
		ids := make([]int32, 0, len(data.Artikel))
		for _, item := range data.Artikel {
			ids = append(ids, item.IDPenulis)
		}
		ctx = loaders.UserLoader.BatchLoad(ctx, ids)
	}

	items := make([]*ArtikelPendingItem, len(data.Artikel))
	for i, item := range data.Artikel {
		items[i] = &ArtikelPendingItem{
			IDArtikel:     int(item.IDArtikel),
			Judul:         item.Judul,
			IDPenulis:     int(item.IDPenulis),
			CreatedAt:     item.CreatedAt,
			StatusArtikel: item.StatusArtikel,
		}
	}

	return &ArtikelPendingPayload{
		Items: items,
		Meta: &PageInfo{
			CurrentPage: int(data.Meta.CurrentPage),
			PerPage:     int(data.Meta.PerPage),
			Total:       int(data.Meta.Total),
			LastPage:    int(data.Meta.LastPage),
		},
	}, nil
}

// Artikel returns ArtikelResolver implementation.
func (r *Resolver) Artikel() ArtikelResolver { return &artikelResolver{r} }

// ArtikelListItem returns ArtikelListItemResolver implementation.
func (r *Resolver) ArtikelListItem() ArtikelListItemResolver { return &artikelListItemResolver{r} }

// ArtikelPendingItem returns ArtikelPendingItemResolver implementation.
func (r *Resolver) ArtikelPendingItem() ArtikelPendingItemResolver {
	return &artikelPendingItemResolver{r}
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type (
	artikelResolver            struct{ *Resolver }
	artikelListItemResolver    struct{ *Resolver }
	artikelPendingItemResolver struct{ *Resolver }
	mutationResolver           struct{ *Resolver }
	queryResolver              struct{ *Resolver }
)
