//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var AuditLog = newAuditLogTable("public", "audit_log", "")

type auditLogTable struct {
	postgres.Table

	// Columns
	IDLog          postgres.ColumnInteger
	IDUser         postgres.ColumnInteger
	Aktivitas      postgres.ColumnString
	IPAddress      postgres.ColumnString
	WaktuAktivitas postgres.ColumnTimestampz

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type AuditLogTable struct {
	auditLogTable

	EXCLUDED auditLogTable
}

// AS creates new AuditLogTable with assigned alias
func (a AuditLogTable) AS(alias string) *AuditLogTable {
	return newAuditLogTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new AuditLogTable with assigned schema name
func (a AuditLogTable) FromSchema(schemaName string) *AuditLogTable {
	return newAuditLogTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new AuditLogTable with assigned table prefix
func (a AuditLogTable) WithPrefix(prefix string) *AuditLogTable {
	return newAuditLogTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new AuditLogTable with assigned table suffix
func (a AuditLogTable) WithSuffix(suffix string) *AuditLogTable {
	return newAuditLogTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newAuditLogTable(schemaName, tableName, alias string) *AuditLogTable {
	return &AuditLogTable{
		auditLogTable: newAuditLogTableImpl(schemaName, tableName, alias),
		EXCLUDED:      newAuditLogTableImpl("", "excluded", ""),
	}
}

func newAuditLogTableImpl(schemaName, tableName, alias string) auditLogTable {
	var (
		IDLogColumn          = postgres.IntegerColumn("id_log")
		IDUserColumn         = postgres.IntegerColumn("id_user")
		AktivitasColumn      = postgres.StringColumn("aktivitas")
		IPAddressColumn      = postgres.StringColumn("ip_address")
		WaktuAktivitasColumn = postgres.TimestampzColumn("waktu_aktivitas")
		allColumns           = postgres.ColumnList{IDLogColumn, IDUserColumn, AktivitasColumn, IPAddressColumn, WaktuAktivitasColumn}
		mutableColumns       = postgres.ColumnList{IDUserColumn, AktivitasColumn, IPAddressColumn, WaktuAktivitasColumn}
		defaultColumns       = postgres.ColumnList{IDLogColumn, WaktuAktivitasColumn}
	)

	return auditLogTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		IDLog:          IDLogColumn,
		IDUser:         IDUserColumn,
		Aktivitas:      AktivitasColumn,
		IPAddress:      IPAddressColumn,
		WaktuAktivitas: WaktuAktivitasColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
