//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var HasilPemeriksaan = newHasilPemeriksaanTable("public", "hasil_pemeriksaan", "")

type hasilPemeriksaanTable struct {
	postgres.Table

	// Columns
	IDHasilPemeriksaan postgres.ColumnInteger
	IDPetugasInput     postgres.ColumnInteger
	IDJadwalImunisasi  postgres.ColumnInteger
	BeratBadan         postgres.ColumnFloat
	TinggiBadan        postgres.ColumnFloat
	LingkarKepala      postgres.ColumnFloat
	TekananDarah       postgres.ColumnString
	StatusStunting     postgres.ColumnString
	StatusGizi         postgres.ColumnString
	Catatan            postgres.ColumnString
	CreatedAt          postgres.ColumnTimestampz
	UpdatedAt          postgres.ColumnTimestampz

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type HasilPemeriksaanTable struct {
	hasilPemeriksaanTable

	EXCLUDED hasilPemeriksaanTable
}

// AS creates new HasilPemeriksaanTable with assigned alias
func (a HasilPemeriksaanTable) AS(alias string) *HasilPemeriksaanTable {
	return newHasilPemeriksaanTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new HasilPemeriksaanTable with assigned schema name
func (a HasilPemeriksaanTable) FromSchema(schemaName string) *HasilPemeriksaanTable {
	return newHasilPemeriksaanTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new HasilPemeriksaanTable with assigned table prefix
func (a HasilPemeriksaanTable) WithPrefix(prefix string) *HasilPemeriksaanTable {
	return newHasilPemeriksaanTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new HasilPemeriksaanTable with assigned table suffix
func (a HasilPemeriksaanTable) WithSuffix(suffix string) *HasilPemeriksaanTable {
	return newHasilPemeriksaanTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newHasilPemeriksaanTable(schemaName, tableName, alias string) *HasilPemeriksaanTable {
	return &HasilPemeriksaanTable{
		hasilPemeriksaanTable: newHasilPemeriksaanTableImpl(schemaName, tableName, alias),
		EXCLUDED:              newHasilPemeriksaanTableImpl("", "excluded", ""),
	}
}

func newHasilPemeriksaanTableImpl(schemaName, tableName, alias string) hasilPemeriksaanTable {
	var (
		IDHasilPemeriksaanColumn = postgres.IntegerColumn("id_hasil_pemeriksaan")
		IDPetugasInputColumn     = postgres.IntegerColumn("id_petugas_input")
		IDJadwalImunisasiColumn  = postgres.IntegerColumn("id_jadwal_imunisasi")
		BeratBadanColumn         = postgres.FloatColumn("berat_badan")
		TinggiBadanColumn        = postgres.FloatColumn("tinggi_badan")
		LingkarKepalaColumn      = postgres.FloatColumn("lingkar_kepala")
		TekananDarahColumn       = postgres.StringColumn("tekanan_darah")
		StatusStuntingColumn     = postgres.StringColumn("status_stunting")
		StatusGiziColumn         = postgres.StringColumn("status_gizi")
		CatatanColumn            = postgres.StringColumn("catatan")
		CreatedAtColumn          = postgres.TimestampzColumn("created_at")
		UpdatedAtColumn          = postgres.TimestampzColumn("updated_at")
		allColumns               = postgres.ColumnList{IDHasilPemeriksaanColumn, IDPetugasInputColumn, IDJadwalImunisasiColumn, BeratBadanColumn, TinggiBadanColumn, LingkarKepalaColumn, TekananDarahColumn, StatusStuntingColumn, StatusGiziColumn, CatatanColumn, CreatedAtColumn, UpdatedAtColumn}
		mutableColumns           = postgres.ColumnList{IDPetugasInputColumn, IDJadwalImunisasiColumn, BeratBadanColumn, TinggiBadanColumn, LingkarKepalaColumn, TekananDarahColumn, StatusStuntingColumn, StatusGiziColumn, CatatanColumn, CreatedAtColumn, UpdatedAtColumn}
		defaultColumns           = postgres.ColumnList{IDHasilPemeriksaanColumn, CreatedAtColumn, UpdatedAtColumn}
	)

	return hasilPemeriksaanTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		IDHasilPemeriksaan: IDHasilPemeriksaanColumn,
		IDPetugasInput:     IDPetugasInputColumn,
		IDJadwalImunisasi:  IDJadwalImunisasiColumn,
		BeratBadan:         BeratBadanColumn,
		TinggiBadan:        TinggiBadanColumn,
		LingkarKepala:      LingkarKepalaColumn,
		TekananDarah:       TekananDarahColumn,
		StatusStunting:     StatusStuntingColumn,
		StatusGizi:         StatusGiziColumn,
		Catatan:            CatatanColumn,
		CreatedAt:          CreatedAtColumn,
		UpdatedAt:          UpdatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
