//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var JadwalImunisasi = newJadwalImunisasiTable("public", "jadwal_imunisasi", "")

type jadwalImunisasiTable struct {
	postgres.Table

	// Columns
	IDImunisasi      postgres.ColumnInteger
	IDPasien         postgres.ColumnInteger
	NamaVaksin       postgres.ColumnString
	TanggalJadwal    postgres.ColumnDate
	TanggalRealisasi postgres.ColumnDate
	StatusImunisasi  postgres.ColumnString
	CreatedAt        postgres.ColumnTimestampz
	UpdatedAt        postgres.ColumnTimestampz

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type JadwalImunisasiTable struct {
	jadwalImunisasiTable

	EXCLUDED jadwalImunisasiTable
}

// AS creates new JadwalImunisasiTable with assigned alias
func (a JadwalImunisasiTable) AS(alias string) *JadwalImunisasiTable {
	return newJadwalImunisasiTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new JadwalImunisasiTable with assigned schema name
func (a JadwalImunisasiTable) FromSchema(schemaName string) *JadwalImunisasiTable {
	return newJadwalImunisasiTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new JadwalImunisasiTable with assigned table prefix
func (a JadwalImunisasiTable) WithPrefix(prefix string) *JadwalImunisasiTable {
	return newJadwalImunisasiTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new JadwalImunisasiTable with assigned table suffix
func (a JadwalImunisasiTable) WithSuffix(suffix string) *JadwalImunisasiTable {
	return newJadwalImunisasiTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newJadwalImunisasiTable(schemaName, tableName, alias string) *JadwalImunisasiTable {
	return &JadwalImunisasiTable{
		jadwalImunisasiTable: newJadwalImunisasiTableImpl(schemaName, tableName, alias),
		EXCLUDED:             newJadwalImunisasiTableImpl("", "excluded", ""),
	}
}

func newJadwalImunisasiTableImpl(schemaName, tableName, alias string) jadwalImunisasiTable {
	var (
		IDImunisasiColumn      = postgres.IntegerColumn("id_imunisasi")
		IDPasienColumn         = postgres.IntegerColumn("id_pasien")
		NamaVaksinColumn       = postgres.StringColumn("nama_vaksin")
		TanggalJadwalColumn    = postgres.DateColumn("tanggal_jadwal")
		TanggalRealisasiColumn = postgres.DateColumn("tanggal_realisasi")
		StatusImunisasiColumn  = postgres.StringColumn("status_imunisasi")
		CreatedAtColumn        = postgres.TimestampzColumn("created_at")
		UpdatedAtColumn        = postgres.TimestampzColumn("updated_at")
		allColumns             = postgres.ColumnList{IDImunisasiColumn, IDPasienColumn, NamaVaksinColumn, TanggalJadwalColumn, TanggalRealisasiColumn, StatusImunisasiColumn, CreatedAtColumn, UpdatedAtColumn}
		mutableColumns         = postgres.ColumnList{IDPasienColumn, NamaVaksinColumn, TanggalJadwalColumn, TanggalRealisasiColumn, StatusImunisasiColumn, CreatedAtColumn, UpdatedAtColumn}
		defaultColumns         = postgres.ColumnList{IDImunisasiColumn, CreatedAtColumn, UpdatedAtColumn}
	)

	return jadwalImunisasiTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		IDImunisasi:      IDImunisasiColumn,
		IDPasien:         IDPasienColumn,
		NamaVaksin:       NamaVaksinColumn,
		TanggalJadwal:    TanggalJadwalColumn,
		TanggalRealisasi: TanggalRealisasiColumn,
		StatusImunisasi:  StatusImunisasiColumn,
		CreatedAt:        CreatedAtColumn,
		UpdatedAt:        UpdatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
