//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var KategoriPendapatan = newKategoriPendapatanTable("public", "kategori_pendapatan", "")

type kategoriPendapatanTable struct {
	postgres.Table

	// Columns
	IDPendapatan       postgres.ColumnInteger
	KategoriPendapatan postgres.ColumnString
	PendapatanMin      postgres.ColumnFloat
	PendapatanMax      postgres.ColumnFloat

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type KategoriPendapatanTable struct {
	kategoriPendapatanTable

	EXCLUDED kategoriPendapatanTable
}

// AS creates new KategoriPendapatanTable with assigned alias
func (a KategoriPendapatanTable) AS(alias string) *KategoriPendapatanTable {
	return newKategoriPendapatanTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new KategoriPendapatanTable with assigned schema name
func (a KategoriPendapatanTable) FromSchema(schemaName string) *KategoriPendapatanTable {
	return newKategoriPendapatanTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new KategoriPendapatanTable with assigned table prefix
func (a KategoriPendapatanTable) WithPrefix(prefix string) *KategoriPendapatanTable {
	return newKategoriPendapatanTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new KategoriPendapatanTable with assigned table suffix
func (a KategoriPendapatanTable) WithSuffix(suffix string) *KategoriPendapatanTable {
	return newKategoriPendapatanTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newKategoriPendapatanTable(schemaName, tableName, alias string) *KategoriPendapatanTable {
	return &KategoriPendapatanTable{
		kategoriPendapatanTable: newKategoriPendapatanTableImpl(schemaName, tableName, alias),
		EXCLUDED:                newKategoriPendapatanTableImpl("", "excluded", ""),
	}
}

func newKategoriPendapatanTableImpl(schemaName, tableName, alias string) kategoriPendapatanTable {
	var (
		IDPendapatanColumn       = postgres.IntegerColumn("id_pendapatan")
		KategoriPendapatanColumn = postgres.StringColumn("kategori_pendapatan")
		PendapatanMinColumn      = postgres.FloatColumn("pendapatan_min")
		PendapatanMaxColumn      = postgres.FloatColumn("pendapatan_max")
		allColumns               = postgres.ColumnList{IDPendapatanColumn, KategoriPendapatanColumn, PendapatanMinColumn, PendapatanMaxColumn}
		mutableColumns           = postgres.ColumnList{KategoriPendapatanColumn, PendapatanMinColumn, PendapatanMaxColumn}
		defaultColumns           = postgres.ColumnList{IDPendapatanColumn}
	)

	return kategoriPendapatanTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		IDPendapatan:       IDPendapatanColumn,
		KategoriPendapatan: KategoriPendapatanColumn,
		PendapatanMin:      PendapatanMinColumn,
		PendapatanMax:      PendapatanMaxColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
