//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var Lokasi = newLokasiTable("public", "lokasi", "")

type lokasiTable struct {
	postgres.Table

	// Columns
	IDLokasi   postgres.ColumnInteger
	NamaLokasi postgres.ColumnString
	TipeLokasi postgres.ColumnString
	BagianDari postgres.ColumnInteger

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type LokasiTable struct {
	lokasiTable

	EXCLUDED lokasiTable
}

// AS creates new LokasiTable with assigned alias
func (a LokasiTable) AS(alias string) *LokasiTable {
	return newLokasiTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new LokasiTable with assigned schema name
func (a LokasiTable) FromSchema(schemaName string) *LokasiTable {
	return newLokasiTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new LokasiTable with assigned table prefix
func (a LokasiTable) WithPrefix(prefix string) *LokasiTable {
	return newLokasiTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new LokasiTable with assigned table suffix
func (a LokasiTable) WithSuffix(suffix string) *LokasiTable {
	return newLokasiTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newLokasiTable(schemaName, tableName, alias string) *LokasiTable {
	return &LokasiTable{
		lokasiTable: newLokasiTableImpl(schemaName, tableName, alias),
		EXCLUDED:    newLokasiTableImpl("", "excluded", ""),
	}
}

func newLokasiTableImpl(schemaName, tableName, alias string) lokasiTable {
	var (
		IDLokasiColumn   = postgres.IntegerColumn("id_lokasi")
		NamaLokasiColumn = postgres.StringColumn("nama_lokasi")
		TipeLokasiColumn = postgres.StringColumn("tipe_lokasi")
		BagianDariColumn = postgres.IntegerColumn("bagian_dari")
		allColumns       = postgres.ColumnList{IDLokasiColumn, NamaLokasiColumn, TipeLokasiColumn, BagianDariColumn}
		mutableColumns   = postgres.ColumnList{NamaLokasiColumn, TipeLokasiColumn, BagianDariColumn}
		defaultColumns   = postgres.ColumnList{IDLokasiColumn}
	)

	return lokasiTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		IDLokasi:   IDLokasiColumn,
		NamaLokasi: NamaLokasiColumn,
		TipeLokasi: TipeLokasiColumn,
		BagianDari: BagianDariColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
