//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var Pekerjaan = newPekerjaanTable("public", "pekerjaan", "")

type pekerjaanTable struct {
	postgres.Table

	// Columns
	IDPekerjaan   postgres.ColumnInteger
	NamaPekerjaan postgres.ColumnString
	Sektor        postgres.ColumnString

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type PekerjaanTable struct {
	pekerjaanTable

	EXCLUDED pekerjaanTable
}

// AS creates new PekerjaanTable with assigned alias
func (a PekerjaanTable) AS(alias string) *PekerjaanTable {
	return newPekerjaanTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new PekerjaanTable with assigned schema name
func (a PekerjaanTable) FromSchema(schemaName string) *PekerjaanTable {
	return newPekerjaanTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new PekerjaanTable with assigned table prefix
func (a PekerjaanTable) WithPrefix(prefix string) *PekerjaanTable {
	return newPekerjaanTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new PekerjaanTable with assigned table suffix
func (a PekerjaanTable) WithSuffix(suffix string) *PekerjaanTable {
	return newPekerjaanTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newPekerjaanTable(schemaName, tableName, alias string) *PekerjaanTable {
	return &PekerjaanTable{
		pekerjaanTable: newPekerjaanTableImpl(schemaName, tableName, alias),
		EXCLUDED:       newPekerjaanTableImpl("", "excluded", ""),
	}
}

func newPekerjaanTableImpl(schemaName, tableName, alias string) pekerjaanTable {
	var (
		IDPekerjaanColumn   = postgres.IntegerColumn("id_pekerjaan")
		NamaPekerjaanColumn = postgres.StringColumn("nama_pekerjaan")
		SektorColumn        = postgres.StringColumn("sektor")
		allColumns          = postgres.ColumnList{IDPekerjaanColumn, NamaPekerjaanColumn, SektorColumn}
		mutableColumns      = postgres.ColumnList{NamaPekerjaanColumn, SektorColumn}
		defaultColumns      = postgres.ColumnList{IDPekerjaanColumn}
	)

	return pekerjaanTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		IDPekerjaan:   IDPekerjaanColumn,
		NamaPekerjaan: NamaPekerjaanColumn,
		Sektor:        SektorColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
