//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var Pendidikan = newPendidikanTable("public", "pendidikan", "")

type pendidikanTable struct {
	postgres.Table

	// Columns
	IDPendidikan   postgres.ColumnInteger
	NamaPendidikan postgres.ColumnString
	Jenjang        postgres.ColumnString
	LamaTahun      postgres.ColumnInteger

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type PendidikanTable struct {
	pendidikanTable

	EXCLUDED pendidikanTable
}

// AS creates new PendidikanTable with assigned alias
func (a PendidikanTable) AS(alias string) *PendidikanTable {
	return newPendidikanTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new PendidikanTable with assigned schema name
func (a PendidikanTable) FromSchema(schemaName string) *PendidikanTable {
	return newPendidikanTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new PendidikanTable with assigned table prefix
func (a PendidikanTable) WithPrefix(prefix string) *PendidikanTable {
	return newPendidikanTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new PendidikanTable with assigned table suffix
func (a PendidikanTable) WithSuffix(suffix string) *PendidikanTable {
	return newPendidikanTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newPendidikanTable(schemaName, tableName, alias string) *PendidikanTable {
	return &PendidikanTable{
		pendidikanTable: newPendidikanTableImpl(schemaName, tableName, alias),
		EXCLUDED:        newPendidikanTableImpl("", "excluded", ""),
	}
}

func newPendidikanTableImpl(schemaName, tableName, alias string) pendidikanTable {
	var (
		IDPendidikanColumn   = postgres.IntegerColumn("id_pendidikan")
		NamaPendidikanColumn = postgres.StringColumn("nama_pendidikan")
		JenjangColumn        = postgres.StringColumn("jenjang")
		LamaTahunColumn      = postgres.IntegerColumn("lama_tahun")
		allColumns           = postgres.ColumnList{IDPendidikanColumn, NamaPendidikanColumn, JenjangColumn, LamaTahunColumn}
		mutableColumns       = postgres.ColumnList{NamaPendidikanColumn, JenjangColumn, LamaTahunColumn}
		defaultColumns       = postgres.ColumnList{IDPendidikanColumn}
	)

	return pendidikanTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		IDPendidikan:   IDPendidikanColumn,
		NamaPendidikan: NamaPendidikanColumn,
		Jenjang:        JenjangColumn,
		LamaTahun:      LamaTahunColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
