//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var Rujukan = newRujukanTable("public", "rujukan", "")

type rujukanTable struct {
	postgres.Table

	// Columns
	IDRujukan      postgres.ColumnInteger
	IDTindakLanjut postgres.ColumnInteger
	AlasanRujukan  postgres.ColumnString
	TanggalRujukan postgres.ColumnDate
	StatusRujukan  postgres.ColumnString
	IDFaskes       postgres.ColumnInteger
	CreatedAt      postgres.ColumnTimestampz
	UpdatedAt      postgres.ColumnTimestampz

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type RujukanTable struct {
	rujukanTable

	EXCLUDED rujukanTable
}

// AS creates new RujukanTable with assigned alias
func (a RujukanTable) AS(alias string) *RujukanTable {
	return newRujukanTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new RujukanTable with assigned schema name
func (a RujukanTable) FromSchema(schemaName string) *RujukanTable {
	return newRujukanTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new RujukanTable with assigned table prefix
func (a RujukanTable) WithPrefix(prefix string) *RujukanTable {
	return newRujukanTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new RujukanTable with assigned table suffix
func (a RujukanTable) WithSuffix(suffix string) *RujukanTable {
	return newRujukanTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newRujukanTable(schemaName, tableName, alias string) *RujukanTable {
	return &RujukanTable{
		rujukanTable: newRujukanTableImpl(schemaName, tableName, alias),
		EXCLUDED:     newRujukanTableImpl("", "excluded", ""),
	}
}

func newRujukanTableImpl(schemaName, tableName, alias string) rujukanTable {
	var (
		IDRujukanColumn      = postgres.IntegerColumn("id_rujukan")
		IDTindakLanjutColumn = postgres.IntegerColumn("id_tindak_lanjut")
		AlasanRujukanColumn  = postgres.StringColumn("alasan_rujukan")
		TanggalRujukanColumn = postgres.DateColumn("tanggal_rujukan")
		StatusRujukanColumn  = postgres.StringColumn("status_rujukan")
		IDFaskesColumn       = postgres.IntegerColumn("id_faskes")
		CreatedAtColumn      = postgres.TimestampzColumn("created_at")
		UpdatedAtColumn      = postgres.TimestampzColumn("updated_at")
		allColumns           = postgres.ColumnList{IDRujukanColumn, IDTindakLanjutColumn, AlasanRujukanColumn, TanggalRujukanColumn, StatusRujukanColumn, IDFaskesColumn, CreatedAtColumn, UpdatedAtColumn}
		mutableColumns       = postgres.ColumnList{IDTindakLanjutColumn, AlasanRujukanColumn, TanggalRujukanColumn, StatusRujukanColumn, IDFaskesColumn, CreatedAtColumn, UpdatedAtColumn}
		defaultColumns       = postgres.ColumnList{IDRujukanColumn, CreatedAtColumn, UpdatedAtColumn}
	)

	return rujukanTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		IDRujukan:      IDRujukanColumn,
		IDTindakLanjut: IDTindakLanjutColumn,
		AlasanRujukan:  AlasanRujukanColumn,
		TanggalRujukan: TanggalRujukanColumn,
		StatusRujukan:  StatusRujukanColumn,
		IDFaskes:       IDFaskesColumn,
		CreatedAt:      CreatedAtColumn,
		UpdatedAt:      UpdatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
