//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var TindakLanjut = newTindakLanjutTable("public", "tindak_lanjut", "")

type tindakLanjutTable struct {
	postgres.Table

	// Columns
	IDTindakLanjut     postgres.ColumnInteger
	IDHasilPemeriksaan postgres.ColumnInteger
	IDBidan            postgres.ColumnInteger
	CatatanMedis       postgres.ColumnString
	Rekomendasi        postgres.ColumnString
	JadwalKontrol      postgres.ColumnDate
	StatusPasien       postgres.ColumnString
	CreatedAt          postgres.ColumnTimestampz
	UpdatedAt          postgres.ColumnTimestampz

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type TindakLanjutTable struct {
	tindakLanjutTable

	EXCLUDED tindakLanjutTable
}

// AS creates new TindakLanjutTable with assigned alias
func (a TindakLanjutTable) AS(alias string) *TindakLanjutTable {
	return newTindakLanjutTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new TindakLanjutTable with assigned schema name
func (a TindakLanjutTable) FromSchema(schemaName string) *TindakLanjutTable {
	return newTindakLanjutTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new TindakLanjutTable with assigned table prefix
func (a TindakLanjutTable) WithPrefix(prefix string) *TindakLanjutTable {
	return newTindakLanjutTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new TindakLanjutTable with assigned table suffix
func (a TindakLanjutTable) WithSuffix(suffix string) *TindakLanjutTable {
	return newTindakLanjutTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newTindakLanjutTable(schemaName, tableName, alias string) *TindakLanjutTable {
	return &TindakLanjutTable{
		tindakLanjutTable: newTindakLanjutTableImpl(schemaName, tableName, alias),
		EXCLUDED:          newTindakLanjutTableImpl("", "excluded", ""),
	}
}

func newTindakLanjutTableImpl(schemaName, tableName, alias string) tindakLanjutTable {
	var (
		IDTindakLanjutColumn     = postgres.IntegerColumn("id_tindak_lanjut")
		IDHasilPemeriksaanColumn = postgres.IntegerColumn("id_hasil_pemeriksaan")
		IDBidanColumn            = postgres.IntegerColumn("id_bidan")
		CatatanMedisColumn       = postgres.StringColumn("catatan_medis")
		RekomendasiColumn        = postgres.StringColumn("rekomendasi")
		JadwalKontrolColumn      = postgres.DateColumn("jadwal_kontrol")
		StatusPasienColumn       = postgres.StringColumn("status_pasien")
		CreatedAtColumn          = postgres.TimestampzColumn("created_at")
		UpdatedAtColumn          = postgres.TimestampzColumn("updated_at")
		allColumns               = postgres.ColumnList{IDTindakLanjutColumn, IDHasilPemeriksaanColumn, IDBidanColumn, CatatanMedisColumn, RekomendasiColumn, JadwalKontrolColumn, StatusPasienColumn, CreatedAtColumn, UpdatedAtColumn}
		mutableColumns           = postgres.ColumnList{IDHasilPemeriksaanColumn, IDBidanColumn, CatatanMedisColumn, RekomendasiColumn, JadwalKontrolColumn, StatusPasienColumn, CreatedAtColumn, UpdatedAtColumn}
		defaultColumns           = postgres.ColumnList{IDTindakLanjutColumn, CreatedAtColumn, UpdatedAtColumn}
	)

	return tindakLanjutTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		IDTindakLanjut:     IDTindakLanjutColumn,
		IDHasilPemeriksaan: IDHasilPemeriksaanColumn,
		IDBidan:            IDBidanColumn,
		CatatanMedis:       CatatanMedisColumn,
		Rekomendasi:        RekomendasiColumn,
		JadwalKontrol:      JadwalKontrolColumn,
		StatusPasien:       StatusPasienColumn,
		CreatedAt:          CreatedAtColumn,
		UpdatedAt:          UpdatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
